[Variables]

; CPU 0
HWiNFO-CPU0-SensorId=0xF0000300
HWiNFO-CPU0-SensorInstance=0x0
HWiNFO-CPU0-Usage=0x7000007

; CPU 0 DTS
HWiNFO-CPU0-DTS-SensorId=0xF0000400
HWiNFO-CPU0-DTS-SensorInstance=0x0
HWiNFO-CPU0-DTS-CoreMax=0x100007f

; Motherboard
HWiNFO-MOBO-SensorId=0xf0008721
HWiNFO-MOBO-SensorInstance=0x0
HWiNFO-MOBO-CPU-Fan=0x3000000

; GPU 0
HWiNFO-GPU0-SensorId=0xe0001800
HWiNFO-GPU0-SensorInstance=0x0
HWiNFO-GPU0-Usage=0x7000000
HWiNFO-GPU0-Temp=0x1000000
HWiNFO-GPU0-Fan=0x3000000

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
